import { defineConfig, devices } from '@playwright/test'

// E2E tests for the syllabus viewer, run against the KULAS-free dummy dataset.
//
// `global-setup.ts` synthesizes a production-scale dataset (a few thousand
// courses, fixed seed → deterministic) if one is not already present, so the
// suite exercises the real load and no test ever contacts KULAS.
export default defineConfig({
	testDir: './e2e',
	fullyParallel: true,
	// Use every core in CI (Playwright otherwise defaults to ~half). '100%' never
	// oversubscribes, so the timing-sensitive geometry specs stay stable.
	workers: process.env.CI ? '100%' : undefined,
	forbidOnly: !!process.env.CI,
	retries: process.env.CI ? 1 : 0,
	reporter: 'list',
	globalSetup: './e2e/global-setup.ts',
	// The dataset is large; give the async (worker-backed) grid room to settle.
	timeout: 45_000,
	expect: {
		timeout: 10_000,
		// Visual baselines are rendered on the CI OS (Linux); a small pixel budget
		// absorbs sub-pixel antialiasing while still catching layout regressions.
		// Baselines are (re)generated by the `visual-baseline` workflow — see
		// e2e/visual.spec.ts and docs/testing.md.
		toHaveScreenshot: { maxDiffPixelRatio: 0.01, animations: 'disabled' },
	},
	use: {
		baseURL: 'http://localhost:5173',
		trace: 'on-first-retry',
		// Headless Chromium throttles rAF/timers in "background" renderers, which
		// makes scroll- and animation-linked assertions flaky. Disable it so the
		// geometry/visual specs observe the same frame timing as a real, focused tab.
		launchOptions: {
			args: [
				'--disable-background-timer-throttling',
				'--disable-renderer-backgrounding',
				'--disable-backgrounding-occluded-windows',
			],
		},
	},
	projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
	webServer: {
		command: 'bun run dev',
		url: 'http://localhost:5173',
		reuseExistingServer: !process.env.CI,
		timeout: 120_000,
	},
})
