import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { defineConfig, devices } from '@playwright/test'
import { prepareE2ePublic } from './e2e/global-setup'

const playwrightTempRoot =
	process.env.E2E_TEMP_ROOT ??
	(process.platform === 'win32'
		? path.join(path.parse(process.cwd()).root, 'tmp')
		: path.join(os.tmpdir(), 'gyakubiki-e2e'))
fs.mkdirSync(playwrightTempRoot, { recursive: true })
const e2ePublicDir =
	process.env.E2E_PUBLIC_DIR ?? fs.mkdtempSync(path.join(playwrightTempRoot, 'gs-e2e-'))
process.env.E2E_TEMP_ROOT = playwrightTempRoot
process.env.E2E_PUBLIC_DIR = e2ePublicDir
prepareE2ePublic(e2ePublicDir, path.resolve(process.cwd(), '..'))

// E2E tests for the syllabus viewer, run against the KULAS-free dummy dataset.
//
// `global-setup.ts` synthesizes a production-scale dataset (a few thousand
// courses, fixed seed → deterministic) if one is not already present, so the
// suite exercises the real load and no test ever contacts KULAS.
export default defineConfig({
	testDir: './e2e',
	fullyParallel: true,
	// Each page initializes WASM and a production-scale dataset. Bound parallelism
	// so browser engines do not compete for enough memory to create false timeouts.
	workers: process.platform === 'win32' ? 1 : 2,
	forbidOnly: !!process.env.CI,
	retries: process.env.CI ? 1 : 0,
	reporter: 'list',
	globalSetup: './e2e/global-setup.ts',
	// The dataset is large; give the async (worker-backed) grid room to settle.
	timeout: 60_000,
	expect: {
		timeout: 15_000,
		// Visual baselines are rendered on the CI OS (Linux); a small pixel budget
		// absorbs sub-pixel antialiasing while still catching layout regressions.
		// Baselines are (re)generated by the `visual-baseline` workflow — see
		// e2e/visual.spec.ts and docs/testing.md.
		toHaveScreenshot: { maxDiffPixelRatio: 0.01, animations: 'disabled' },
	},
	use: {
		baseURL: 'http://localhost:4517',
		trace: 'on-first-retry',
	},
	projects: [
		{
			name: 'chromium',
			use: {
				...devices['Desktop Chrome'],
				// Keep geometry/timer assertions deterministic in headless Chromium.
				launchOptions: {
					args: [
						'--disable-background-timer-throttling',
						'--disable-renderer-backgrounding',
						'--disable-backgrounding-occluded-windows',
					],
				},
			},
		},
		{
			name: 'firefox-smoke',
			testMatch: /app\.spec\.ts/,
			fullyParallel: false,
			use: { ...devices['Desktop Firefox'] },
		},
		{
			name: 'webkit-smoke',
			testMatch: /app\.spec\.ts/,
			fullyParallel: false,
			use: { ...devices['Desktop Safari'] },
		},
	],
	// A dedicated port: on 5173, `reuseExistingServer` happily adopts whatever
	// unrelated Vite dev server happens to be running and every test fails on a
	// foreign page. strictPort makes a leftover occupant fail loudly instead.
	webServer: {
		command: 'bun run dev:e2e',
		url: 'http://127.0.0.1:4517/',
		env: {
			E2E_PUBLIC_DIR: e2ePublicDir,
			E2E_TEMP_ROOT: playwrightTempRoot,
			VITE_E2E: 'true',
		},
		reuseExistingServer: !process.env.CI,
		timeout: 180_000,
	},
})
